# Generated by Django 3.0.1 on 2019-12-31 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='athor',
            new_name='author',
        ),
    ]
